### PR TITLE
Update Drupal 8 boilerplate to Drupal 8.5.4

### PR DESCRIPTION
**Pull request by shelane**
I ran `fin init` from the project, then `fin drush up` to get the updated Drupal code.

### CODE REVIEW

**Comment by achekulaev** [comment]
Did you run `fin init` on the updated core to check it still works by any chance?

**Comment by shelane** [comment]
Yes I did. In both the master branch and the 8.5.4 branch, there is this error message:
```
error sending mail
2018/07/04 02:22:35 dial tcp: lookup mail on 127.0.0.11:53: no such host
```
I suspect that it comes from this line in the `fin init-site` command:
```
	# We disable email sending here so site-install does not return an error
	php -d sendmail_path=/bin/true /usr/local/bin/drush site-install -y --site-name='My Drupal 8 Site'
```

I have just used the standard `drupal si` commands on my sites without an issue. My pull request isn't modifying the init command file though.

**Comment by achekulaev** [comment]
> I have just used the standard drupal si commands on my sites without an issue

This is a good comment, thanks. @lmakarov should we remove sendmail_path from that line maybe?

**Comment by lmakarov** [comment]
Thanks for the core update @shelane 

@achekulaev 

`php -d sendmail_path=/bin/true` is there to actually fix the issue with no mail server available in the default stack. I remember an issue with Drush 8 not supporting passing PHP variables via ENV

This fix for that happened here:
https://github.com/docksal/drupal8/commit/9eca2bc54e052a648e8667ed53b0f595a30d63ba

Looks like that fix now also does not work. I'm going to create a separate issue for that.

**Pull request merged**
